name: ceo2-shi
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - numpy=1.26.*
  - scipy=1.13.*
  - pandas=2.2.*
  - matplotlib=3.8.*
  - pyyaml=6.0.*
  - ruamel.yaml=0.18.*
  - ase=3.23.*
  - h5py=3.11.*
  - tqdm=4.*
  - ipython
  - jupyterlab
  - pip:
      - ovito==3.10.6

